### ISSUE TITLE
A SEGV signal occurred in CNN+ATT/init.h: 71

### ISSUE THREAD

**Issue by fCorleone** [thunlp/NRE#27]
When I ran the test program in CNN+ATT, a SEGV signal occurred in init.h:71
```
=================================================================
==25628==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000c0 (pc 0x7fa794dc2908 bp 0x7ffca4461380 sp 0x7ffca4460ca0 T0)
    #0 0x7fa794dc2907 in _IO_vfscanf (/lib/x86_64-linux-gnu/libc.so.6+0x5b907)
    #1 0x7fa795c415d0 in vfscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x525d0)
    #2 0x7fa795c41749 in __interceptor_fscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x52749)
    #3 0x402c1e in init() /home/mfc_fuzz/NRE/CNN+ATT/init.h:71
    #4 0x40e400 in main /home/mfc_fuzz/NRE/CNN+ATT/test.cpp:99
    #5 0x7fa794d8782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x4028e8 in _start (/home/mfc_fuzz/NRE/CNN+ATT/test+0x4028e8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 _IO_vfscanf
==25628==ABORTING
```

**Comment by fCorleone** [comment]
And another SEGV signal in CNN+ONE/init.h:69
```
=================================================================
==29722==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000c0 (pc 0x7f55d54b3908 bp 0x7ffce9be4280 sp 0x7ffce9be3ba0 T0)
    #0 0x7f55d54b3907 in _IO_vfscanf (/lib/x86_64-linux-gnu/libc.so.6+0x5b907)
    #1 0x7f55d63325d0 in vfscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x525d0)
    #2 0x7f55d6332749 in __interceptor_fscanf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x52749)
    #3 0x402c5d in init() /home/mfc_fuzz/NRE/CNN+ONE/init.h:69
    #4 0x40d204 in main /home/mfc_fuzz/NRE/CNN+ONE/test.cpp:84
    #5 0x7f55d547882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x4028d8 in _start (/home/mfc_fuzz/NRE/CNN+ONE/test+0x4028d8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 _IO_vfscanf
==29722==ABORTING
```

**Comment by Mrlyk423** [comment]
Please check if the data folder is in the correct position.
